Repository bcgov/bcparks-staff-portal, pull requests merged in 2025-07, with the labels that each got.

#227 CMS-987: Fix filtering status
  frontend/src/router/pages/EditAndReview.jsx
Labels: v0.1.3

#223 CMS-907: Add gate detail table
  backend/middleware/adminJs.js
  backend/migrations/20250618230715-create-gate-detail.js
  backend/models/gatedetail.js
  backend/models/index.js
  backend/models/publishable.js
  backend/strapi-sync/reset-and-import-data.js
  backend/strapi-sync/sync.js
  backend/tasks/create-gate-details/README.md
  backend/tasks/create-gate-details/create-gate-details.js
  backend/tasks/populate-park-gate-dates/README.md
  backend/tasks/populate-park-gate-dates/populate-park-gate-dates.js
Labels: v0.1.3

#226 CMS-872: Add is date range annual to park form and feature form
  backend/models/datetype.js
  backend/models/publishable.js
  backend/routes/api/seasons.js
  frontend/src/components/DateRangeFields.jsx
  frontend/src/components/SeasonForms/AreaSeasonForm.jsx
  frontend/src/components/SeasonForms/FeatureSeasonForm.jsx
  frontend/src/components/SeasonForms/ParkSeasonForm.jsx
Labels: v0.1.3

#231 CMS-872: Save is date range annual update
  backend/routes/api/seasons.js
  frontend/src/components/FormPanel.jsx
  frontend/src/components/SeasonForms/AreaSeasonForm.jsx
  frontend/src/components/SeasonForms/FeatureSeasonForm.jsx
  frontend/src/components/SeasonForms/ParkSeasonForm.jsx
Labels: v0.1.3

#230 CMS-907: Update gate form
  backend/routes/api/seasons.js
  frontend/src/components/DateRangeForm.jsx
  frontend/src/components/FormPanel.jsx
  frontend/src/components/GateForm.jsx
  frontend/src/components/SeasonForms/AreaSeasonForm.jsx
  frontend/src/components/SeasonForms/FeatureSeasonForm.jsx
  frontend/src/components/SeasonForms/ParkSeasonForm.jsx
  frontend/src/components/TimeRangeForm.jsx
  frontend/src/lib/utils.js
Labels: v0.1.3

#232 CMS-929: Add modal windows and navigation guard
  frontend/src/components/ConfirmationDialog.scss
  frontend/src/components/FormPanel.jsx
  frontend/src/hooks/useConfirmation.js
  frontend/src/hooks/useMissingDatesConfirmation.js
  frontend/src/hooks/useNavigationGuard.js
  frontend/src/router/pages/EditAndReview.jsx
  frontend/src/router/pages/PublishPage.jsx
Labels: v0.1.4

#241 CMS-996: Fix crash when opening month dropdown
  frontend/src/components/DatePicker.jsx
  frontend/src/components/DateRangeFields.jsx
  frontend/src/styles/_datepicker.scss
Labels: v0.1.3

#242 CMS-929: Fix "Move back to draft?" prompt check
  frontend/src/components/FormPanel.jsx
Labels: v0.1.4

#243 CMS-898: Fix return value for getSeasonPark
  backend/utils/propagateWinterFeeDates.js
Labels: v0.1.3

#240 CMS-1065: Add default time when it is focused
  frontend/src/components/DateRangeFields.jsx
  frontend/src/components/GateForm.jsx
  frontend/src/components/SeasonForms/AreaSeasonForm.jsx
  frontend/src/components/TimeRangeForm.jsx
Labels: v0.1.3

#229 CMS-905: Add banner on test site
  frontend/src/router/layouts/MainLayout.jsx
  frontend/src/router/layouts/MainLayout.scss
Labels: v0.1.4

#239 CMS-1043: Populate date ranges if dates are the same every year
  backend/tasks/create-date-range-annual/README.md
  backend/tasks/create-gate-details/README.md
  backend/tasks/create-seasons.js
  backend/tasks/populate-date-ranges/README.md
  backend/tasks/populate-date-ranges/populate-date-ranges.js
  backend/tasks/populate-park-gate-dates/README.md
Labels: v0.1.3

#248 CMS-1070: Omit Area-level dates from Area form
  backend/routes/api/seasons.js
Labels: v0.1.3

#252 CMS-898: Temporarily disable winter fee propagation to features
  backend/routes/api/parks.js
  backend/routes/api/seasons.js
Labels: v0.1.3

#255 CMS-1087: Fall back to checking T1/T2/Winter if BCP Res. check is false
  frontend/src/components/SeasonForms/ParkSeasonForm.jsx
Labels: v0.1.3

#238 CMS-1014: Implement approve button on table rows
  frontend/src/components/EditAndReviewTable.jsx
  frontend/src/contexts/RefreshTableContext.js
  frontend/src/router/pages/EditAndReview.jsx
Labels: v0.1.4

#263 CMS-1119: Remove operating dates from table if park has hasGate false
  backend/routes/api/parks.js
  frontend/src/components/FormPanel.jsx
Labels: v0.1.4

#266 CMS-1089: Add error page for login
  frontend/src/components/Unauthorized.jsx
  frontend/src/router/AccessProvider.jsx
  frontend/src/router/layouts/MainLayout.jsx
Labels: v0.1.4

#270 CMS-1129: Fix bcparks.ca typo
  frontend/src/components/FormPanel.jsx
Labels: v0.1.4

#267 CMS-960: Part 2 Add BCeID login to V2 app
  frontend-legacy/src/components/page/home/Home.js
  frontend/src/hooks/useAccess.js
  frontend/src/router/AccessProvider.jsx
  frontend/src/router/ProtectedRoute.jsx
  frontend/src/router/index.jsx
  frontend/src/router/layouts/MainLayout.jsx
  frontend/src/router/pages/LoginPage.jsx
  frontend/src/router/pages/LoginPage.scss
Labels: v0.1.4

#268 CMS-970: Bulk create blank dates
  backend/migrations/20250724232555-add-backcountry-permits-feature-col.js
  backend/models/feature.js
  backend/routes/api/seasons.js
  backend/strapi-sync/sync.js
  backend/tasks/create-seasons.js
  backend/tasks/populate-date-ranges/README.md
  backend/tasks/populate-date-ranges/populate-annual-date-ranges.js
  backend/tasks/populate-date-ranges/populate-blank-date-ranges.js
  backend/utils/dateTypesHelpers.js
Labels: v0.1.5

#274 CMS-1045: Use username instead of email for AccessGroups
  .gitignore
  backend/middleware/users.js
  backend/migrations/20250729210202-add-username-col.js
  backend/migrations/20250730001613-add-username-to-useraccessgroups.js
  backend/migrations/20250730002814-remove-email-constraints-from-useraccessgroups.js
  backend/migrations/20250730004622-add-username-constraints.js
  backend/models/accessgroup.js
  backend/models/user.js
  backend/models/useraccessgroup.js
  backend/tasks/populate-access-groups/README.md
  backend/tasks/populate-access-groups/agreement-example.json
  backend/tasks/populate-access-groups/populate-access-groups.js
Labels: v0.1.4
