Repository bcgov/bcparks-staff-portal, pull requests merged in 2025-08, with the labels that each got.

#278 CMS-1082: Add "Optional" labels, disable "X" for single dates
  frontend/src/components/DateRangeFields.jsx
  frontend/src/components/GateForm.jsx
  frontend/src/components/SeasonForms/AreaSeasonForm.jsx
  frontend/src/components/SeasonForms/FeatureSeasonForm.jsx
  frontend/src/components/SeasonForms/ParkSeasonForm.jsx
  frontend/src/lib/isDateTypeOptional.js
  frontend/src/styles/global.scss
Labels: v0.1.5

#284 CMS-324: Always reset AccessGroups tables when populating new bundles
  backend/tasks/populate-access-groups/populate-access-groups.js
Labels: v0.1.5, v2.0.0

#298 CMS-970: Remove early return before creating blank gate dates
  backend/tasks/populate-date-ranges/populate-blank-date-ranges.js
Labels: v2.0.0

#293 CMS-1156: Update gate form wording
  backend/routes/api/filter-options.js
  backend/routes/api/parks.js
  backend/strapi-sync/sync.js
  backend/tasks/create-date-types/README.md
  backend/tasks/create-date-types/create-date-types.js
  backend/tasks/create-date-types/date-types.js
  frontend/src/components/GateForm.jsx
  frontend/src/components/SeasonForms/ParkSeasonForm.jsx
Labels: v2.0.0

#295 CMS-1020: Use park area publishable id for group camping feature seasons
  backend/routes/api/parks.js
  backend/tasks/create-seasons.js
Labels: v2.0.0

#296 CMS-1097: Filter parks by hasGate
  backend/routes/api/parks.js
  frontend/src/router/pages/EditAndReview.jsx
Labels: v2.0.0

#297 CMS-1083: Update DOOT URL
  frontend-legacy/entrypoint.sh
  frontend-legacy/src/components/composite/header/Header.css
  frontend-legacy/src/components/composite/header/Header.js
  frontend-legacy/src/components/composite/responsiveDrawer/responsiveDrawer.js
  frontend-legacy/src/components/page/appDashboard/AppDashboard.js
  frontend/Caddyfile
  frontend/Dockerfile.prod
  frontend/src/config/keycloak.js
  frontend/src/router/index.jsx
  frontend/vite.config.js
  helm/deployment/templates/frontend/frontend-deployment.yaml
Labels: v2.0.0

#302 CMS-510: Add "completeDateRanges" validation rule
  frontend/src/hooks/useValidation/rules/completeDateRanges.js
  frontend/src/hooks/useValidation/useValidation.js
Labels: v2.0.0

#303 CMS-970: Fix season/dateRange filter in create-blank-gate-dates
  backend/tasks/populate-date-ranges/populate-blank-gate-dates.js
Labels: v2.0.0

#305 CMS-1176: Allow save draft if there are validation errors
  frontend/src/components/FormPanel.jsx
  frontend/src/hooks/useValidation/useValidation.js
Labels: v2.0.0

#299 CMS-874: Show/hide nav menu items depending on user permissions
  frontend-legacy/src/components/composite/responsiveDrawer/responsiveDrawer.js
  frontend-legacy/src/components/page/appDashboard/AppDashboard.js
  frontend/src/components/NavSidebar.jsx
  frontend/src/components/TouchMenu.jsx
  frontend/src/components/shared/navItems.js
  frontend/src/config/permissions.js
  frontend/src/hooks/useAccess.js
Labels: v2.0.0

#308 CMS-1185: Add a filter to previous dates at feature in park area level
  frontend/src/components/SeasonForms/AreaSeasonForm.jsx
Labels: v2.0.0

#300 CMS-947: Update filter for bcp reservations
  backend/migrations/20250818235750-add-in-reservation-system-field-to-parkarea.js
  backend/models/parkarea.js
  backend/routes/api/parks.js
  backend/tasks/populate-in-reservation-system/README.md
  backend/tasks/populate-in-reservation-system/populate-in-reservation-system.js
  frontend/src/components/FilterPanel.jsx
  frontend/src/router/pages/EditAndReview.jsx
Labels: v2.0.0

#306 CMS-1132: Add a script to re sync all data from scratch
  backend/strapi-sync/reset-and-import-data.js
  backend/tasks/create-date-types/create-date-types.js
  backend/tasks/create-gate-details/create-gate-details.js
  backend/tasks/populate-park-tier-types/populate-park-tier-types.js
  backend/tasks/populate-park-winter-fee-flag/populate-park-winter-fee-flag.js
  backend/tasks/re-sync-all/README.md
  backend/tasks/re-sync-all/delete-all.js
  backend/tasks/re-sync-all/re-sync-all.js
Labels: v2.0.0

#320 CMS-1132: Update 2025 tier data
  backend/tasks/populate-park-tier-types/2025-tier-data.json
Labels: v2.0.0
